name = "wedding-computer"
main = "src/index.tsx"
compatibility_date = "2025-05-01"
account_id = "56eb0a25e23b5ed8e20b17842ccc14df"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "wedding-computer-db"
database_id = "b20a6a12-b588-4107-9ab1-7eea58fde6d0"

[[kv_namespaces]]
binding = "KV"
id = "c62f7d1f22174f7da3617d1f0257e398"

[[queues.producers]]
binding = "EMAIL_QUEUE"
queue = "wedding-computer-emails"

[[queues.consumers]]
queue = "wedding-computer-emails"
max_batch_size = 10
max_retries = 3

[vars]
APP_URL = "https://wedding.computer"
TURNSTILE_SITE_KEY = "placeholder"

[observability.logs]
enabled = true
invocation_logs = true

[triggers]
crons = ["0 20 * * *"]
