/**
 * vendors.md — who's on a wedding, exported to the vendor's vault.
 *
 * Generated and read-only (like log.md): membership is managed through
 * invites in the app, never by editing a file. The export respects the
 * couple's vendor_visibility setting — when the couple keeps their vendor
 * list private, a vendor's copy shows only the couple and themselves.
 *
 * Couple-private data (couple_vendors.notes, expected_price_cents) is
 * never exported here.
 */

import { getWeddingMembers } from './weddings'
import { listCoupleVendors } from './couple-vendors'
import type { Wedding } from '../types'

/**
 * Snapshot of what vendors.md renders from, stored in the file_index row's
 * cached_data so the push sweep can tell when the file needs regenerating.
 * Must mirror the aggregates in storage-sync's stale-candidate query.
 */
export async function vendorsCachedData(
  db: D1Database,
  weddingId: string
): Promise<string> {
  const members = await db
    .prepare(
      `SELECT COUNT(*) AS mc, MAX(COALESCE(accepted_at, created_at)) AS ml
       FROM wedding_members WHERE wedding_id = ? AND status = 'active'`
    )
    .bind(weddingId)
    .first<{ mc: number; ml: string | null }>()
  const coupleVendors = await db
    .prepare(
      `SELECT COUNT(*) AS cv, MAX(updated_at) AS cvl
       FROM couple_vendors WHERE wedding_id = ? AND status != 'removed'`
    )
    .bind(weddingId)
    .first<{ cv: number; cvl: string | null }>()
  return JSON.stringify({
    mc: members?.mc ?? 0,
    ml: members?.ml ?? null,
    cv: coupleVendors?.cv ?? 0,
    cvl: coupleVendors?.cvl ?? null,
  })
}

export async function exportWeddingVendorsMarkdown(
  db: D1Database,
  wedding: Pick<Wedding, 'id' | 'title' | 'vendor_visibility'>,
  viewerVendorId: string
): Promise<string> {
  const members = await getWeddingMembers(db, wedding.id)
  const visible = wedding.vendor_visibility === 'visible'

  const vendorMembers = members.filter(
    (m) => m.role === 'vendor' && (visible || m.vendor_profile_id === viewerVendorId)
  )
  const coupleMembers = members.filter((m) => m.role === 'couple')

  const lines: string[] = [
    `# ${wedding.title} — Vendors`,
    '',
    '_Generated by Wedding Computer. This file is read-only — manage the wedding team in the app._',
    '',
  ]

  if (coupleMembers.length > 0) {
    lines.push('## Couple', '')
    for (const m of coupleMembers) {
      const contact = m.user_email ? ` — ${m.user_email}` : ''
      lines.push(`- **${m.user_name || m.user_email || 'Couple member'}**${contact}`)
    }
    lines.push('')
  }

  lines.push('## Wedding team', '')
  if (vendorMembers.length === 0) {
    lines.push('_No vendors yet._', '')
  }
  for (const m of vendorMembers) {
    const name = m.business_name || m.user_name || m.user_email || 'Vendor'
    const role = m.vendor_role ? ` — ${m.vendor_role}` : ''
    const manager = m.can_manage ? ' · manager' : ''
    const you = m.vendor_profile_id === viewerVendorId ? ' · you' : ''
    lines.push(`- **${name}**${role}${manager}${you}`)
    const details: string[] = []
    if (m.user_name && m.business_name) details.push(m.user_name)
    if (m.user_email) details.push(m.user_email)
    if (m.vendor_website) details.push(m.vendor_website)
    if (m.vendor_instagram) details.push(`@${m.vendor_instagram.replace(/^@/, '')}`)
    if (details.length > 0) lines.push(`  - ${details.join(' · ')}`)
  }
  lines.push('')

  if (visible) {
    // The couple's own vendor list, minus rows that duplicate a platform
    // member above and minus everything the couple keeps private.
    const memberProfileIds = new Set(
      vendorMembers.map((m) => m.vendor_profile_id).filter(Boolean)
    )
    const coupleVendors = (await listCoupleVendors(db, wedding.id)).filter(
      (cv) => !cv.vendor_profile_id || !memberProfileIds.has(cv.vendor_profile_id)
    )
    if (coupleVendors.length > 0) {
      lines.push("## Couple's vendor list", '')
      for (const cv of coupleVendors) {
        const role = cv.category ? ` — ${cv.category}` : ''
        lines.push(`- **${cv.name}**${role} · ${cv.status}`)
        const details: string[] = []
        if (cv.email) details.push(cv.email)
        if (cv.phone) details.push(cv.phone)
        if (cv.website) details.push(cv.website)
        if (cv.instagram) details.push(`@${cv.instagram.replace(/^@/, '')}`)
        if (details.length > 0) lines.push(`  - ${details.join(' · ')}`)
      }
      lines.push('')
    }
  } else {
    lines.push('_The couple keeps their full vendor list private; only your own listing is shown._', '')
  }

  return lines.join('\n')
}
